# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dimensioning.ui'
#
# Created: Mon May 16 22:43:32 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dimensioning(object):
    def setupUi(self, Dimensioning):
        Dimensioning.setObjectName("Dimensioning")
        Dimensioning.resize(391, 245)
        self.gridLayout_2 = QtGui.QGridLayout(Dimensioning)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnAdd = QtGui.QPushButton(Dimensioning)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_3.addWidget(self.btnAdd)
        self.btnCancel = QtGui.QPushButton(Dimensioning)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(Dimensioning)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sboxLayerId = QtGui.QSpinBox(Dimensioning)
        self.sboxLayerId.setObjectName("sboxLayerId")
        self.horizontalLayout_4.addWidget(self.sboxLayerId)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtGui.QLabel(Dimensioning)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sboxLength = QtGui.QDoubleSpinBox(Dimensioning)
        self.sboxLength.setProperty("value", 0.0)
        self.sboxLength.setObjectName("sboxLength")
        self.horizontalLayout_6.addWidget(self.sboxLength)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblA = QtGui.QLabel(Dimensioning)
        self.lblA.setObjectName("lblA")
        self.horizontalLayout_7.addWidget(self.lblA)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblO = QtGui.QLabel(Dimensioning)
        self.lblO.setObjectName("lblO")
        self.horizontalLayout_8.addWidget(self.lblO)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sboxStartOffset = QtGui.QDoubleSpinBox(Dimensioning)
        self.sboxStartOffset.setProperty("value", 0.0)
        self.sboxStartOffset.setObjectName("sboxStartOffset")
        self.horizontalLayout_9.addWidget(self.sboxStartOffset)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 3, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sboxEndOffset = QtGui.QDoubleSpinBox(Dimensioning)
        self.sboxEndOffset.setProperty("value", 0.0)
        self.sboxEndOffset.setObjectName("sboxEndOffset")
        self.horizontalLayout_10.addWidget(self.sboxEndOffset)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 4, 1, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.chckBoxInvert = QtGui.QCheckBox(Dimensioning)
        self.chckBoxInvert.setObjectName("chckBoxInvert")
        self.horizontalLayout_11.addWidget(self.chckBoxInvert)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dimensioning)
        QtCore.QMetaObject.connectSlotsByName(Dimensioning)

    def retranslateUi(self, Dimensioning):
        Dimensioning.setWindowTitle(QtGui.QApplication.translate("Dimensioning", "Dimensioning", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("Dimensioning", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("Dimensioning", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dimensioning", "Layer ID: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dimensioning", "Length: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblA.setText(QtGui.QApplication.translate("Dimensioning", "Start Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblO.setText(QtGui.QApplication.translate("Dimensioning", "End Offset: ", None, QtGui.QApplication.UnicodeUTF8))
        self.chckBoxInvert.setText(QtGui.QApplication.translate("Dimensioning", "Invert", None, QtGui.QApplication.UnicodeUTF8))

